### ISSUE TITLE
just add texts

### ISSUE THREAD

**Issue by asptvr** [asptvr/web-project#3]
nothig just write

**Comment by allensphilip** [comment]
SSAsa

**Comment by allensphilip** [comment]
HI JUST TEXT ITS GONNA BE ADDED

**Comment by JatinSingh08** [comment]
Hey @allensphilip assign this to me.

**Comment by allensphilip** [comment]
> Hey @allensphilip assign this to me.

What do you mean

**Comment by sahil-rathi** [comment]
Please correct the hacktoberfest-accepted label

**Comment by asptvr** [comment]
> Please correct the hacktoberfest-accepted label

please make another pull request then I will assign that label
